### ISSUE TITLE
Should we switch from 🌩 to ⛈ ?

### ISSUE THREAD

**Issue by JJJ** [JJJ/publishiza#5]
I think I like the raining cloud better.

And the poo will probably need to go eventually, but I'm quite fond of the lil guy.

**Comment by felixarntz** [comment]
I think it all depends on how the target audience sees it. Can they accept the fun way of marketing? I can definitely see people not liking to have the poo in their tweets. Maybe it could go away, but there should be a filter to adjust the emojis or (easier) a constant just to bring the poo back.

Maybe there could even be a setting in WP Admin with some predefined choices, similar like for the default gravatar, for the users who don't wanna deal with constants or code in general (maybe only show this if constant is not set?).

Related to the actual question in this issue, I think I prefer the raining cloud, too.

**Comment by MichaelArestad** [comment]
💩-be-gone setting for some serious 💩🌩s. Problem solved. Also, I think the one without the rain is a clearer icon.

**Comment by JJJ** [comment]
Will keep 🌩 for now, and add a setting for customizing the prefix.
