### ISSUE TITLE
private keys in code

### ISSUE THREAD

**Issue by ghost** [JJJ/publishiza#6]
Hi,

Are you really sure about that ? I've used this API quite often and [at that time] this seemed to be bad practice to use private keys in code. These keys are probably your keys, so it can be stolen to run spam campaigns not to mention illegal things.

[I said "at that time" but I don't see why this would have changed].

I've done this wrapper and it's workin fine without any private keys in code https://github.com/tweetpressfr/tokentome, there are probably a lot of libraries but this one is done the WP way. At least it tries to be wp-friendly :) 

Please consider this. Your application (created with dev.twitter.com) could be blacklisted.
Regards.

**Comment by JJJ** [comment]
Hey @tweetpressfr, thanks for opening this issue.

I'm not 100% sure about this, so I appreciate you noticing and having a solution on deck.

I've looked at yours, and I don't understand how it is different that what Keyring does. Yours seems to still need to pass in the key and secret, and there's no way to get a token without them.

I'd considered the following approaches:

* Obfuscation, but this can just be reverse engineered
* Keeping key/secret remote, but these would still need to be publicly accessible
* Not having a Twitter app, and forcing users to go through the process of making their own Twitter app for their own blog. This is likely what needs to happen, but boy is it a truly bad experience.
* Just hiding the keys in the code and hoping nobody would find them, but eventually someone would find them anyways, so I didn't bother being very coy about it

Once this becomes a problem – and I'm sure that it will pretty quickly – I'll just need to go with #3 above and walk users through the process. Or maybe a combination of 1 and 2, and hope it's enough work that nobody is interested in undoing it.

It's also totally possible I've missed a very obvious solution, or am overthinking the problem, so I'm very open to changing this if possible.

**Comment by ghost** [comment]
In fact, I usually connect this class to some kinda of options, you know typical settings in WordPress such as an option page, so the keys and the token remains private.

This force people to create their own application on dev.twitter.com with their own tokens and it's not so difficult, they just need a Twitter account. 

If you want to skip the application part, my best advice would be to add some SIGN IN process so your users would sign in with their own account. That's the best way, your application would just ask them some permissions to do its job.

The experience would be fine this way, I go to the option page, I sign in with my Twitter account and then I enjoy publishiza :)

**Comment by JJJ** [comment]
This is – for sure – the way this should probably go.

For discussion sake:

> it can be stolen to run spam campaigns not to mention illegal things

Is the thought that hiding these in the database is adequate obfuscation, compared to hiding them in the code? I guess because both seem so easily accessible to site-owners (largely the target audience here) that, to me, it doesn't seem worth the level-of-effort.

Again, not trying to be critical; I'm legitimately curious if there's a way to not give the secret away somehow (aside from locking the keys behind another door with other keys.)

**Comment by ghost** [comment]
For now the keys are used directly in code so anybody who has an internet connection can use them if you prefer. In fact I would never have shared these keys publicly. Huge huge flaw.

This has nothing to do with someone stealing an account with appropriate access to get the information. It requires some skills AND opportunity. Not sure if you see what I mean by sign in process so check this https://dev.twitter.com/web/sign-in

Anyway it's up to you :)

**Comment by JJJ** [comment]
> Huge huge flaw.

It seems to me like storing keys anywhere client side is a huge flaw, but that there's also not a clear way around the need to do so without other remote middleware. Am I understanding your point correctly?

And if I haven't made it clear yet, I am 100% on board with not having the keys here. I knew from the get-go it wasn't ideal, and knew we'd figure out a better way eventually.

Thanks again for this back and forth. I appreciate your helping out and working around my daftness.
